name: hpysdk
channels:
  - conda-forge
  - https://repo.platform.here.com/artifactory/api/conda/olp_analytics/analytics_sdk
dependencies:
  - python=3.9
  - leafmap
  - emacs
  - seaborn
  - jupyterlab
  - ipydatagrid
  - ray-core
  - voila
  - lux-api
  - streamlit
  - fastapi
  - xyzspaces
  - here-location-services
  - here-map-widget-for-jupyter
  - here-content=2.4.0
  - here-geopandas-adapter=2.4.0
  - here-geotiles=2.4.0
  - here-inspector=2.4.0
  - here-platform=2.4.0
